### ISSUE TITLE
xen:balloon: cannot add additional memory(-17) and no  more netmap buffer objects

### ISSUE THREAD

**Issue by pengminjiong** [cnplab/clickos#13]
After installed clickos and xennet. I  recreated part of the results of "ClickOS and the Art of Network Function Virtualization".(throughput  part of some middleboxes). I can create 100 VMs(clickos) without using VALE(xennet) but only created 38 clickos vms with VALE(xennet).
Error message after exceed 38 VMs  : not enough netmap buffer objects
                               xen:balloon: cannot add additional memory(-17)
                               ibxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/vif-vale online [-1] exited with error status 1
libxl: error: libxl_device.c:1085:device_hotplug_child_death_cb: script: /etc/xen/scripts/vif-vale failed; error detected.
libxl: error: libxl_create.c:1226:domcreate_attach_vtpms: unable to add nic devices

Can you tell me how to enlarge netmap buffer or other solutions ?

**Comment by jpemartins** [comment]
One (quick) way of creating more interfaces is to reload the xennet netback kernel module with these mod params: default_tx_desc=64 default_rx_desc=64.

The other one is taking a lot at the pool parameters in netmap_mem2.c and playing and increase them further. Since the ring size is 1024 by default you won't 100 as it need big pools of contigous pages. So try decreasing and seeing your balance.

Perhaps this is a better question to xennet than clickos.

Cheers

**Comment by pengminjiong** [comment]
Sorry to bother you again. you helped me a lot in previous months about installing clickos.
I followed your advices  " insmod xen-netback.ko default_tx_desc=64 default_rx_desc=64 " and the VMs numbers reached 50 , after 50   


the same error :   not enough netmap buffer objects
xen:balloon: cannot add additional memory(-17)
ibxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/vif-vale online [-1] exited with error status 1
libxl: error: libxl_device.c:1085:device_hotplug_child_death_cb: script: /etc/xen/scripts/vif-vale failed; error detected.
libxl: error: libxl_create.c:1226:domcreate_attach_vtpms: unable to add nic device
 
cannot create more than 50 even set  default_tx_desc= 24 default_rx_desc=24


In netmap_mem2.c,  which part should I change for creating more VMs ? ( I  tried to change several parts  but have no impacts on  creating VMs , after change source code, I recompiled xennet by  running " cd ; cd rennet/LINUX ; make" )


static int netmap_mem_global_config(struct netmap_mem_d *nmd);
static int netmap_mem_global_finalize(struct netmap_mem_d *nmd);
static void netmap_mem_global_deref(struct netmap_mem_d *nmd);
struct netmap_mem_d nm_mem = {  /* Our memory allocator. */
        .pools = {
                [NETMAP_IF_POOL] = {
                        .name   = "netmap_if",
                        .objminsize = sizeof(struct netmap_if),
                        .objmaxsize = 4096,
                        .nummin     = 10,       /* don't be stingy */
                        .nummax     = 10000,    /* XXX very large */
                },
                [NETMAP_RING_POOL] = {
                        .name   = "netmap_ring",
                        .objminsize = sizeof(struct netmap_ring),
                        .objmaxsize = 32*PAGE_SIZE,
                        .nummin     = 2,
                        .nummax     = 2024,
                },
                [NETMAP_BUF_POOL] = {
                        .name   = "netmap_buf",
                        .objminsize = 64,
                        .objmaxsize = 85536,
                        .nummin     = 4,
                        .nummax     = 1000000, /* one million! */
                },
        },
        .config   = netmap_mem_global_config,
        .finalize = netmap_mem_global_finalize,
        .deref    = netmap_mem_global_deref,

        .nm_id = 1,

        .prev = &nm_mem,
        .next = &nm_mem,
};


struct netmap_mem_d *netmap_last_mem_d = &nm_mem;
// XXX logically belongs to nm_mem
struct lut_entry *netmap_buffer_lut;    /* exported */

/* blueprint for the private memory allocators */
static int netmap_mem_private_config(struct netmap_mem_d *nmd);
static int netmap_mem_private_finalize(struct netmap_mem_d *nmd);
static void netmap_mem_private_deref(struct netmap_mem_d *nmd);
const struct netmap_mem_d nm_blueprint = {
        .pools = {
                [NETMAP_IF_POOL] = {
                        .name   = "%s_if",
                        .objminsize = sizeof(struct netmap_if),
                        .objmaxsize = 4096,
                        .nummin     = 1,
                        .nummax     = 100,
                },
                [NETMAP_RING_POOL] = {
                        .name   = "%s_ring",
                        .objminsize = sizeof(struct netmap_ring),
                        .objmaxsize = 32*PAGE_SIZE,
                        .nummin     = 2,
                        .nummax     = 1024,
                },
                [NETMAP_BUF_POOL] = {
                        .name   = "%s_buf",
                        .objminsize = 64,
                        .objmaxsize = 65536,
                        .nummin     = 4,
                        .nummax     = 1000000, /* one million! */
                },
        },
        .config   = netmap_mem_private_config,
        .finalize = netmap_mem_private_finalize,
        .deref    = netmap_mem_private_deref,

        .flags = NETMAP_MEM_PRIVATE,
};

/* memory allocator related sysctls */


  Thank you again.

**Comment by jpemartins** [comment]
You need to increase the number of netmap buffer objects (in all pools) in nm_mem. Try just doubling them, And you also need to check when you reload the module if the allocation succedded. the global allocator uses contiguous pages allocator for these buffers (__get_free_pages) and its a bit limited.

Also about the xen balloon issue Try increasing your balloon size, and you should also increase the numer of frames for the grant table to say 64 frames which is reasonable (search for the boot parameter in xen documentation)

**Comment by pengminjiong** [comment]
Sorry  for troubling you 
I failed to double buffer pools
Because, after recompiled ,all the modifications that I made return to default numbers again.
I tried doubled pools in mem2.c (also  doubled  netmap_mem2.h:#define NETMAP_BUF_MAX_NUM 20*4096*2).  
I recompiled  by those commands:
 $cd LINUX
 $ make KSRC=/usr/src/linux-3.13.0 prepare
 $ make KSRC=/usr/src/linux-headers-3.13.0-generic
Please told me how to recompile after doubled buffer pools( I cannot find which code that may keep all source code in default version for safety).
Thank you very much.

**Comment by jpemartins** [comment]
After compiling the first time, you can make your changes and then You only need the last "make". The make prepare part does a git reset --hard which is why your changes werent applied.

**Comment by pengminjiong** [comment]
I tried that way but does not work. " does not work",  I mean I added some word like print hello in "netmap_obj_mallocto" which print  "no more netmap_ring objects" in dmesg.

**Comment by jpemartins** [comment]
Might be that netmap is not even building. The xennet Makefile looks and the Module.symvers. The solution might to just build netmap and the build xennet. Try repeating that last command in xennet/netmap/LINUX.

**Comment by pengminjiong** [comment]
I definitely reloaded all modules. 
Here is what I did :

nano netmap_mem2.c
enter "hello" into netmap_obj_malloc" 
                if (p->objfree == 0) {
                D(" hello no more %s objects", p->name);
                return NULL;
make KSRC=...
But the output of make :  
make KSRC=/usr/src/linux-headers-3.13.0-62-generic
make KBUILD_EXTRA_SYMBOLS=/root/xennet/netmap/LINUX/Module.symvers -C /usr/src/linux-headers-3.13.0-62-generic \
		EXTRA_CFLAGS='-I/root/xennet/LINUX -I/root/xennet/netmap/LINUX -I/root/xennet/netmap/sys/dev/netmap -I/root/xennet/netmap/sys/net -I/root/xennet/netmap/sys/dev -I/root/xennet/LINUX/xen-netback -Wno-format -Wno-unused-function -DCONFIG_NETMAP' M=/root/xennet/LINUX \
		CONFIG_DEBUG_INFO=y CONFIG_NETMAP_XENBUS=y CONFIG_NETMAP=y
make[1]: Entering directory `/usr/src/linux-headers-3.13.0-62-generic'
  CC [M]  /root/xennet/LINUX/xen-netback/netback.o
  CC [M]  /root/xennet/LINUX/xen-netback/xenbus.o
  CC [M]  /root/xennet/LINUX/xen-netback/interface.o
  LD [M]  /root/xennet/LINUX/xen-netback/xen-netback.o
  CC [M]  /root/xennet/LINUX/xen-netfront/xen-netfront.o
  Building modules, stage 2.
MODPOST 2 modules
  CC      /root/xennet/LINUX/xen-netback/xen-netback.mod.o
  LD [M]  /root/xennet/LINUX/xen-netback/xen-netback.ko
  CC      /root/xennet/LINUX/xen-netfront/xen-netfront.mod.o
  LD [M]  /root/xennet/LINUX/xen-netfront/xen-netfront.ko
make[1]: Leaving directory `/usr/src/linux-headers-3.13.0-62-generic'

reload netmap_lin.ko xen-netback.ko ixgbe.ko
create 55 VMs
failed when port number reach 50,
check dmesg 
still only print "no more netmap_ring objects"

then  I tried to add "hello" in netmap.c(netmap_set_ringid ,   deprecated API, old ringid)
make KSRC=...
reload modules
create 1 VMs
In dmesg still print "deprecated API, old ringid 0x0 -> ringid 0 reg 1"

So  netmap.c and netmap_mem2.c do not be compiled well.

**Comment by jpemartins** [comment]
I meant to do just rebuild netmap without using xennet makefiles. From the trace it disnt look that netmap was rebuilt.

Try also doing: 1) make clean; cd xennet/netmap/LINUX; make clean; cd -; make prepare 2) do your change 3) make

**Comment by pengminjiong** [comment]
Thanks  a lot.
you can close this issue.
I really appreciate for your help.

peng

Best wishes
