### ISSUE TITLE
Obtaining the value of 'count'

### ISSUE THREAD

**Issue by hassanjameel1** [cnplab/clickos#2]
Hi,

This might be a very naive question.

It seems that ClickOS excludes the click element 'Script' (and in turn the 'DriverManager' element). How would you then be able to print say the value of 'count' for the AverageCounter element? Is there is a way to print this value through another element or obtain it through some log files?

I am using the set-up mentioned in your "Getting Started" page for building ClickOS.

Best wishes,
Hassan

**Comment by hassanjameel1** [comment]
Hi.

I think I found the answer myself after playing with cosmos. For a ClickOS instance named 'clickos', an AverageCounter element named actr, the 'count' attribute can be obtained as:

cosmos read clickos actr count

Best wishes,
Hassan

**Comment by jpemartins** [comment]
Hey Hassan,

Sorry for long response, but looks like you found the answer yourself.
You also have write element handlers, e.g. 'reset_counts' in 'Counter' element named ctr. This will set packet count to 0. For that you have an additional argument:

```
cosmos write clickos ctr reset_counts 1
```

Thanks!
