### ISSUE TITLE
Router init failed

### ISSUE THREAD

**Issue by wenhuizhang** [cnplab/clickos#21]
Hi, I was wondering if there are some specific requirements for bridge and other network MAC/IP configuration requirements ?

# xl console clickos
Xen Minimal OS!
  start_info: 0x1bf000(VA)
    nr_pages: 0x800
  shared_inf: 0xbf4b6000(MA)
     pt_base: 0x1c2000(VA)
nr_pt_frames: 0x5
    mfn_list: 0x1bb000(VA)
   mod_start: 0x0(VA)
     mod_len: 0
       flags: 0x0
    cmd_line: 
  stack:      0x178040-0x198040
MM: Init
      _text: 0x0(VA)
     _etext: 0xe163d(VA)
   _erodata: 0x15e000(VA)
     _edata: 0x15fbb8(VA)
stack start: 0x178040(VA)
       _end: 0x1ba010(VA)
  start_pfn: 1ca
    max_pfn: 800
Mapping memory range 0x400000 - 0x800000
setting 0x0-0x15e000 readonly
skipped 0x1000
MM: Initialise page allocator for 1cc000(1cc000)-800000(800000)
MM: done
Demand map pfns at 801000-2000801000.
Heap resides at 2000802000-4000802000.
Initialising timer interface
Initialising console ... done.
gnttab_table mapped at 0x801000.
Initialising scheduler
Thread "Idle": pointer: 0x2000802050, stack: 0x1e0000
Thread "xenstore": pointer: 0x2000802800, stack: 0x1f0000
xenbus initialised on irq 1 mfn 0x4ac5c0
Thread "shutdown": pointer: 0x2000802fb0, stack: 0x200000
Dummy main: start_info=0x198040
Thread "main": pointer: 0x2000803760, stack: 0x210000
sparsing 0MB at 177000
"main" 
[on_status:205] router id 0
[on_status:206] status change to Running
Thread "click": pointer: 0x20008110b0, stack: 0x230000
config:21: undeclared element 'd'
Failed to read /local/domain/0/backend/vif/10/0/feature-netmap.
************************ NETFRONT for device/vif/0 **********

net TX ring size 256
net RX ring size 256
backend at /local/domain/0/backend/vif/10/0
mac is aa:00:00:00:00:00
**************************
Router could not be initialized!
close network: backend at /local/domain/0/backend/vif/10/0
[router_thread:149] Router init failed!
Thread "click" exited.

**Comment by fmanco** [comment]
I'm not sure what you mean by requirements, but reading the console output there's an error on your click configuration file on line 21:

```
config:21: undeclared element 'd'
```

**Comment by wenhuizhang** [comment]
Hi, I think I used exactly the example of "firewall.click"
http://cnp.neclab.eu/getting-started#clickos

**Comment by fmanco** [comment]
Indeed this example is broken. I updated the page with a working example. Please take a look and let me know.

Filipe

**Comment by wenhuizhang** [comment]
Hi, Fillipe:

The new scripts on website still does not work: 

```
wenhui@nimbnode34:~$ sudo xl console 16
Xen Minimal OS!
  start_info: 0x1bf000(VA)
    nr_pages: 0x800
  shared_inf: 0xbf4b6000(MA)
     pt_base: 0x1c2000(VA)
nr_pt_frames: 0x5
    mfn_list: 0x1bb000(VA)
   mod_start: 0x0(VA)
     mod_len: 0
       flags: 0x0
    cmd_line: 
  stack:      0x178040-0x198040
MM: Init
      _text: 0x0(VA)
     _etext: 0xe163d(VA)
   _erodata: 0x15e000(VA)
     _edata: 0x15fbb8(VA)
stack start: 0x178040(VA)
       _end: 0x1ba010(VA)
  start_pfn: 1ca
    max_pfn: 800
Mapping memory range 0x400000 - 0x800000
setting 0x0-0x15e000 readonly
skipped 0x1000
MM: Initialise page allocator for 1cc000(1cc000)-800000(800000)
MM: done
Demand map pfns at 801000-2000801000.
Heap resides at 2000802000-4000802000.
Initialising timer interface
Initialising console ... done.
gnttab_table mapped at 0x801000.
Initialising scheduler
Thread "Idle": pointer: 0x2000802050, stack: 0x1e0000
Thread "xenstore": pointer: 0x2000802800, stack: 0x1f0000
xenbus initialised on irq 1 mfn 0x4ac5c0
Thread "shutdown": pointer: 0x2000802fb0, stack: 0x200000
Dummy main: start_info=0x198040
Thread "main": pointer: 0x2000803760, stack: 0x210000
sparsing 0MB at 177000
"main" 
[on_status:205] router id 0
[on_status:206] status change to Running
Thread "click": pointer: 0x2000810d30, stack: 0x230000
Failed to read device/vif/1/backend-id.
_init_netfront: backend/mac failed
```
It works for ponger though:

```
wenhui@nimbnode34:~$ sudo xl console 2
[sudo] password for wenhui: 
Xen Minimal OS!
  start_info: 0x1bf000(VA)
    nr_pages: 0x800
  shared_inf: 0xbf4b6000(MA)
     pt_base: 0x1c2000(VA)
nr_pt_frames: 0x5
    mfn_list: 0x1bb000(VA)
   mod_start: 0x0(VA)
     mod_len: 0
       flags: 0x0
    cmd_line: 
  stack:      0x178040-0x198040
MM: Init
      _text: 0x0(VA)
     _etext: 0xe163d(VA)
   _erodata: 0x15e000(VA)
     _edata: 0x15fbb8(VA)
stack start: 0x178040(VA)
       _end: 0x1ba010(VA)
  start_pfn: 1ca
    max_pfn: 800
Mapping memory range 0x400000 - 0x800000
setting 0x0-0x15e000 readonly
skipped 0x1000
MM: Initialise page allocator for 1cc000(1cc000)-800000(800000)
MM: done
Demand map pfns at 801000-2000801000.
Heap resides at 2000802000-4000802000.
Initialising timer interface
Initialising console ... done.
gnttab_table mapped at 0x801000.
Initialising scheduler
Thread "Idle": pointer: 0x2000802050, stack: 0x1e0000
Thread "xenstore": pointer: 0x2000802800, stack: 0x1f0000
xenbus initialised on irq 1 mfn 0x4a8dc0
Thread "shutdown": pointer: 0x2000802fb0, stack: 0x200000
Dummy main: start_info=0x198040
Thread "main": pointer: 0x2000803760, stack: 0x210000
sparsing 0MB at 177000
"main" 
[on_status:205] router id 0
[on_status:206] status change to Running
Thread "click": pointer: 0x2000810ca0, stack: 0x230000
Failed to read /local/domain/0/backend/vif/2/0/feature-netmap.
************************ NETFRONT for device/vif/0 **********


net TX ring size 256
net RX ring size 256
backend at /local/domain/0/backend/vif/2/0
mac is aa:bb:cc:dd:ee:ff
**************************
[router_thread:157] Starting driver...
```

**Comment by fmanco** [comment]
This new configuration has 2 interfaces.

**Comment by wenhuizhang** [comment]
Does that mean I should create 2 bridges with different ip assigned according to dhcp , and bind them to the same eth0?

**Comment by fmanco** [comment]
Take a look at the click configuration, it's written to be easy to understand.

Basically you have the wan interface (first VIF) and lan interface (second VIF). This transparent firewall allows packets from wan to lan going to a specific IP and allows everything from lan to wan.

This means you need two bridges. The way you setup IP addresses is up to you, the firewall is transparent so doesn't need IP. The only assumption (that you can anyway change) is that a "server" in the lan network has address `10.0.0.1`.

**Comment by wenhuizhang** [comment]
Hi, Fillipe, sorry for bothering, yet do you mind if provide a link to basic grammar goes on here? I want to set up a multi NF chain to test it on a single machine in diff vms.

**Comment by fmanco** [comment]
Hi

ClickOS is Click with some extensions for MiniOS support, therefore the upstream documentation applies except for MiniOS specific `FromDevice` and `ToDevice`.

You can find the docs at http://read.cs.ucla.edu/click/click.

Best regards

**Comment by wenhuizhang** [comment]
Thanks so much Fillipe, I am looking into it :) :+1:

**Comment by fmanco** [comment]
No problem. I'll close this since it's fixed. Fell free to open another issue if needed.
