### ISSUE TITLE
Failed to use clickos-ctl to install a router 

### ISSUE THREAD

**Issue by stevepp** [cnplab/clickos#28]
I have been using cosmos to start and stop a router instance. Yesterday I tried to use clickos-ctl to install a click configuration. The clickos-ctl an be compiled without any problem. However, when I tried to install a click configuration as follows:

clickos install -s click0 ponger.click

I got the message "Domain click0, doesn't seem to be a ClickOS domain". The click0 domain image was compiled before I use clickos-ctl. Do I need to pull the latest clickos source code and recompile a new image so as to use clickos-ctl?

**Comment by fmanco** [comment]
Hello

Indeed, clickos-ctl depends on the changes introduced by #17. Also be sure to update clickos-ctl since I just merged a PR that fixes an argument parsing bug.

**Comment by stevepp** [comment]
Finally I can use clickos-ctl to install click configuration now. However, it only works with small configuration file such as ponger.click or mirror.click. For large configuration file such as mazu-nat.click, I didn't see the router instance created. Instead I can only see the main thread created. 

Does clickos-ctl gracefully handle writing large configuration file through xenstore? I know that cosmos can split the config file into segments and write them into the clickos instance.

**Comment by fmanco** [comment]
There is indeed a problem with large configurations. I suspect it has something to do we the chunk size I'm using. I'll look into it. Would you mind opening an issue against clickos-ctl? I'll close this one since it's not related with clickos anymore.

Thank you
