### ISSUE TITLE
ClickOS - no response after some time and hangs

### ISSUE THREAD

**Issue by musigit** [cnplab/clickos#40]
I am trying the simple ping response example with latest ClickOS from master. I have tried this on both Ubuntu 14.04 LTS Update 5 as well as Ubuntu 16.04 Update 3 LTS with stock Xen.

After initial success, the Click OS setup stops responding to ping request after some time. To rule out any issues with network setup, I have used both linux bridge as well as Open vSwitch .. both end up with similar issues. What could be the reason? Is there something I have missed out and what should I be looking at?

Please note that I have tried this on multiple Ubuntu + Xen systems. The clickos vm reponds to 'xl shutdown' ... so it doesn't seem to have crashed.

Minimal debug attempt  - I recompiled minios with debug dprintk enabled and with that I don't see any "rx: --- " output in console once it hangs.
```
+++
/** commented out
#define dprintk(format, ...)	do {} while(0)
*/

#ifndef dprintk
#define dprintk(format, ...)	printk(format,##__VA_ARGS__)
#endif
+++

Last few lines of xl console output before hang - 

rx: ring: len 98
rx: --- 98 bytes
Ping Response:   98 | 00161715 5d190050 56b52ef4 08004500 00540c29 0000ff01
tx: raw 98
rx: ring: len 98
rx: --- 98 bytes
Ping Response:   98 | 00161715 5d190050 56b52ef4 08004500 00540cb5 0000ff01
tx: raw 98
```

Here is my simple test config -
```icmp.click

// define the IP address of this network function.
// This IP must NOT be the same with your VM's IP.
define($IP 192.168.44.29);
// This MAC must be identical with the one you defined in config.xen
define($MAC 00:16:17:15:5d:19);

source :: FromDevice;
sink   :: ToDevice;
c :: Classifier(
    12/0806 20/0001,
    12/0806 20/0002,
    12/0800,
    -);

arpq :: ARPQuerier($IP, $MAC);
arpr :: ARPResponder($IP $MAC);  // No comma here.

source -> c;
c[0] -> ARPPrint -> arpr -> sink;
c[1] -> [1]arpq;
Idle -> [0]arpq;
arpq -> ARPPrint -> sink;
c[2] -> CheckIPHeader(14) -> ICMPPingResponder() -> Print('Ping Response') -> EtherMirror() -> sink;
c[3] -> Discard;
```
xen config
```
name   = 'firsttest'
kernel = '/home/tester/workspace/clickos/minios/build/clickos_x86_64'
vcpus  = '1'
# pinning your VCPU helps performance
cpus   = '3'
memory = '128'

# uncoment this line if you wish to use our backend
#vif    = ['bridge=vale0,script=vif-vale']
vif    = ['script=vif-openvswitch,mac=00:16:17:15:5d:19,bridge=ovsbr1,model=e1000']

on_poweroff = 'destroy'
on_reboot   = 'restart'
on_crash    = 'preserve'
click       = 'mirror.click'

# uncomment this line to enable PVH mode for ClickOS
#pvh=1
```

**Comment by fmanco** [comment]
Hi

Is this deterministic, i.e., always hangs after the same number of pings? Also, what is the state of the VM after it hangs, running or blocked?

One thing you could try is to use [uniprof](https://github.com/cnplab/uniprof) to get a stack trace of the VM once it hangs, to try to understand where it is blocked.

Finally, please post the full output of the VM up to immediately after you install the configuration.

Thanks

**Comment by musigit** [comment]
Thanks for looking at this.

Initially I thought it was random because it failed at various points. Today, I took various counts with an isolated linux bridge with pings from dom0. The count is pretty much consistent .. .here is what I have for 64 bytes ICMP pings.

Trial - Count
1 - 217
2 - 221
3 - 224
4 - 224
5 - 224
6 - 224
7 - 221
8 - 224

The state of the VM when ping hangs is running as far as a I can say from uniprof trace (A dump for 2 seconds interval is attached. Last few traces .. for about 10 secs are after ping response stopped).

Xen Host details - It is a 4 vCPU, 10GB VM
+++++++++++++++++++++++++++
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

sudo xl dmesg | grep "Xen version"
(XEN) Xen version 4.6.5 (Ubuntu 4.6.5-0ubuntu1.2) (stefan.bader@canonical.com) (gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609) debug=n Tue Jul 18 12:05:49 UTC 2017

The full output of VM  - 
+++++++++++++++
Xen Minimal OS!
  start_info: 0x213000(VA)
    nr_pages: 0x8000
  shared_inf: 0xbfcba000(MA)
     pt_base: 0x216000(VA)
nr_pt_frames: 0x5
    mfn_list: 0x1d3000(VA)
   mod_start: 0x0(VA)
     mod_len: 0
       flags: 0x0
    cmd_line:
  stack:      0x1900c0-0x1b00c0
MM: Init
      _text: 0x0(VA)
     _etext: 0x101f3a(VA)
   _erodata: 0x17b000(VA)
     _edata: 0x17cb98(VA)
stack start: 0x1900c0(VA)
       _end: 0x1d2010(VA)
  start_pfn: 21e
    max_pfn: 8000
Mapping memory range 0x21e000 - 0x8000000
setting 0x0-0x17b000 readonly
skipped 0x1000
MM: Initialise page allocator for 25c000(25c000)-8000000(8000000)
MM: done
Demand map pfns at 8001000-2008001000.
Heap resides at 2008002000-4008002000.
Initialising timer interface
Initialising console ... done.
gnttab_table mapped at 0x8001000.
Initialising scheduler
Thread "Idle": pointer: 0x2008002050, stack: 0x270000
Thread "xenstore": pointer: 0x2008002800, stack: 0x280000
xenbus initialised on irq 1 mfn 0x1bca14
Thread "shutdown": pointer: 0x2008002fb0, stack: 0x290000
Dummy main: start_info=0x1b00c0
Thread "main": pointer: 0x2008003760, stack: 0x2a0000
sparsing 0MB at 18f000
"main"
[on_status:217] router id 0
[on_status:218] status change to Running
Thread "click": pointer: 0x2008010cf0, stack: 0x2c0000
Failed to read /local/domain/0/backend/vif/6/0/feature-netmap.
************************ NETFRONT for device/vif/0 **********


net TX ring size 256, 1024 KB
net RX ring size 256, 1024 KB buffer space
split event channels enabled
backend at /local/domain/0/backend/vif/6/0
mac is 00:16:17:15:5d:69
**************************
[router_thread:158] Starting driver...


[uniprof-trace.txt](https://github.com/cnplab/clickos/files/1215763/uniprof-trace.txt)

**Comment by musigit** [comment]
Additional log for - 'xl -vvv create xen-config/firsttest.cfg'
+++++++++++++++++++++++++++++++++++++

Parsing config from xen-config/firsttest.cfg
libxl: debug: libxl_create.c:1563:do_domain_create: ao 0x1da77e0: create: how=(nil) callback=(nil) poller=0x1da7a90
libxl: debug: libxl_create.c:947:initiate_domain_create: running bootloader
libxl: debug: libxl_bootloader.c:330:libxl__bootloader_run: no bootloader configured, using user supplied kernel
libxl: debug: libxl_event.c:691:libxl__ev_xswatch_deregister: watch w=0x1da5418: deregister unregistered
domainbuilder: detail: xc_dom_allocate: cmdline="(null)", features="(null)"
libxl: debug: libxl_dom.c:625:libxl__build_pv: pv kernel mapped 0 path /home/tester/workspace/clickos/minios/build/clickos_x86_64
domainbuilder: detail: xc_dom_kernel_file: filename="/home/tester/workspace/clickos/minios/build/clickos_x86_64"
domainbuilder: detail: xc_dom_malloc_filemap    : 1640 kB
domainbuilder: detail: xc_dom_boot_xen_init: ver 4.6, caps xen-3.0-x86_64 xen-3.0-x86_32p 
domainbuilder: detail: xc_dom_parse_image: called
domainbuilder: detail: xc_dom_find_loader: trying multiboot-binary loader ... 
domainbuilder: detail: loader probe failed
domainbuilder: detail: xc_dom_find_loader: trying Linux bzImage loader ... 
domainbuilder: detail: xc_dom_probe_bzimage_kernel: kernel is not a bzImage
domainbuilder: detail: loader probe failed
domainbuilder: detail: xc_dom_find_loader: trying ELF-generic loader ... 
domainbuilder: detail: loader probe OK
xc: detail: elf_parse_binary: phdr: paddr=0x0 memsz=0x1d2010
xc: detail: elf_parse_binary: memory: 0x0 -> 0x1d2010
xc: detail: elf_xen_parse: __xen_guest: "GUEST_OS=Mini-OS,XEN_VER=xen-3.0,VIRT_BASE=0x0,ELF_PADDR_OFFSET=0x0,HYPERCALL_PAGE=0x2,LOADER=generic,FEATURES=!writable_descriptor_tables|hvm_callback_vector|auto_translated_physmap|supervisor_mode_kernel"
xc: detail: elf_xen_parse_guest_info: GUEST_OS="Mini-OS"
xc: detail: elf_xen_parse_guest_info: XEN_VER="xen-3.0"
xc: detail: elf_xen_parse_guest_info: VIRT_BASE="0x0"
xc: detail: elf_xen_parse_guest_info: ELF_PADDR_OFFSET="0x0"
xc: detail: elf_xen_parse_guest_info: HYPERCALL_PAGE="0x2"
xc: detail: elf_xen_parse_guest_info: LOADER="generic"
xc: detail: elf_xen_parse_guest_info: FEATURES="!writable_descriptor_tables|hvm_callback_vector|auto_translated_physmap|supervisor_mode_kernel"
xc: detail: elf_xen_addr_calc_check: addresses:
xc: detail:     virt_base        = 0x0
xc: detail:     elf_paddr_offset = 0x0
xc: detail:     virt_offset      = 0x0
xc: detail:     virt_kstart      = 0x0
xc: detail:     virt_kend        = 0x1d2010
xc: detail:     virt_entry       = 0x0
xc: detail:     p2m_base         = 0xffffffffffffffff
domainbuilder: detail: xc_dom_parse_elf_kernel: xen-3.0-x86_64: 0x0 -> 0x1d2010
domainbuilder: detail: xc_dom_mem_init: mem 128 MB, pages 0x8000 pages, 4k each
domainbuilder: detail: xc_dom_mem_init: 0x8000 pages
domainbuilder: detail: xc_dom_boot_mem_init: called
domainbuilder: detail: x86_compat: guest xen-3.0-x86_64, address size 64
domainbuilder: detail: xc_dom_malloc            : 256 kB
domainbuilder: detail: xc_dom_build_image: called
domainbuilder: detail: xc_dom_alloc_segment:   kernel       : 0x0 -> 0x1d3000  (pfn 0x0 + 0x1d3 pages)
domainbuilder: detail: xc_dom_pfn_to_ptr_retcount: domU mapping: pfn 0x0+0x1d3 at 0x7fe8406ba000
xc: detail: elf_load_binary: phdr 0 at 0x7fe8406ba000 -> 0x7fe840836b98
domainbuilder: detail: xc_dom_alloc_segment:   phys2mach    : 0x1d3000 -> 0x213000  (pfn 0x1d3 + 0x40 pages)
domainbuilder: detail: xc_dom_pfn_to_ptr_retcount: domU mapping: pfn 0x1d3+0x40 at 0x7fe84067a000
domainbuilder: detail: xc_dom_alloc_page   :   start info   : 0x213000 (pfn 0x213)
domainbuilder: detail: xc_dom_alloc_page   :   xenstore     : 0x214000 (pfn 0x214)
domainbuilder: detail: xc_dom_alloc_page   :   console      : 0x215000 (pfn 0x215)
domainbuilder: detail: nr_page_tables: 0x0000ffffffffffff/48: 0x0000000000000000 -> 0x0000ffffffffffff, 1 table(s)
domainbuilder: detail: nr_page_tables: 0x0000007fffffffff/39: 0x0000000000000000 -> 0x0000007fffffffff, 1 table(s)
domainbuilder: detail: nr_page_tables: 0x000000003fffffff/30: 0x0000000000000000 -> 0x000000003fffffff, 1 table(s)
domainbuilder: detail: nr_page_tables: 0x00000000001fffff/21: 0x0000000000000000 -> 0x00000000003fffff, 2 table(s)
domainbuilder: detail: xc_dom_alloc_segment:   page tables  : 0x216000 -> 0x21b000  (pfn 0x216 + 0x5 pages)
domainbuilder: detail: xc_dom_pfn_to_ptr_retcount: domU mapping: pfn 0x216+0x5 at 0x7fe842824000
domainbuilder: detail: xc_dom_alloc_page   :   boot stack   : 0x21b000 (pfn 0x21b)
domainbuilder: detail: xc_dom_build_image  : virt_alloc_end : 0x21c000
domainbuilder: detail: xc_dom_build_image  : virt_pgtab_end : 0x400000
domainbuilder: detail: xc_dom_boot_image: called
domainbuilder: detail: arch_setup_bootearly: doing nothing
domainbuilder: detail: xc_dom_compat_check: supported guest type: xen-3.0-x86_64 <= matches
domainbuilder: detail: xc_dom_compat_check: supported guest type: xen-3.0-x86_32p
domainbuilder: detail: xc_dom_update_guest_p2m: dst 64bit, pages 0x8000
domainbuilder: detail: clear_page: pfn 0x215, mfn 0x1bca15
domainbuilder: detail: clear_page: pfn 0x214, mfn 0x1bca14
domainbuilder: detail: xc_dom_pfn_to_ptr_retcount: domU mapping: pfn 0x213+0x1 at 0x7fe842821000
domainbuilder: detail: start_info_x86_64: called
domainbuilder: detail: setup_hypercall_page: vaddr=0x2000 pfn=0x2
domainbuilder: detail: domain builder memory footprint
domainbuilder: detail:    allocated
domainbuilder: detail:       malloc             : 271 kB
domainbuilder: detail:       anon mmap          : 0 bytes
domainbuilder: detail:    mapped
domainbuilder: detail:       file mmap          : 1640 kB
domainbuilder: detail:       domU mmap          : 2148 kB
domainbuilder: detail: arch_setup_bootlate: shared_info: pfn 0x0, mfn 0xbfcba
domainbuilder: detail: shared_info_x86_64: called
domainbuilder: detail: vcpu_x86_64: called
domainbuilder: detail: vcpu_x86_64: cr3: pfn 0x216 mfn 0x1bca16
domainbuilder: detail: launch_vm: called, ctxt=0x7fe842822004
domainbuilder: detail: xc_dom_release: called
libxl: debug: libxl_event.c:639:libxl__ev_xswatch_register: watch w=0x1da8b20 wpath=/local/domain/0/backend/vif/10/0/state token=3/0: register slotnum=3
libxl: debug: libxl_create.c:1586:do_domain_create: ao 0x1da77e0: inprogress: poller=0x1da7a90, flags=i
libxl: debug: libxl_event.c:576:watchfd_callback: watch w=0x1da8b20 wpath=/local/domain/0/backend/vif/10/0/state token=3/0: event epath=/local/domain/0/backend/vif/10/0/state
libxl: debug: libxl_event.c:884:devstate_callback: backend /local/domain/0/backend/vif/10/0/state wanted state 2 still waiting state 1
libxl: debug: libxl_event.c:576:watchfd_callback: watch w=0x1da8b20 wpath=/local/domain/0/backend/vif/10/0/state token=3/0: event epath=/local/domain/0/backend/vif/10/0/state
libxl: debug: libxl_event.c:880:devstate_callback: backend /local/domain/0/backend/vif/10/0/state wanted state 2 ok
libxl: debug: libxl_event.c:677:libxl__ev_xswatch_deregister: watch w=0x1da8b20 wpath=/local/domain/0/backend/vif/10/0/state token=3/0: deregister slotnum=3
libxl: debug: libxl_device.c:991:device_backend_callback: calling device_backend_cleanup
libxl: debug: libxl_event.c:691:libxl__ev_xswatch_deregister: watch w=0x1da8b20: deregister unregistered
libxl: debug: libxl_device.c:1088:device_hotplug: calling hotplug script: /etc/xen/scripts/vif-bridge online
libxl: debug: libxl_aoutils.c:593:libxl__async_exec_start: forking to execute: /etc/xen/scripts/vif-bridge online 
libxl: debug: libxl_event.c:691:libxl__ev_xswatch_deregister: watch w=0x1da8c20: deregister unregistered
libxl: debug: libxl_device.c:1075:device_hotplug: No hotplug script to execute
libxl: debug: libxl_event.c:691:libxl__ev_xswatch_deregister: watch w=0x1da8c20: deregister unregistered
libxl: debug: libxl_event.c:2183:libxl__ao_progress_report: ao 0x1da77e0: progress report: ignored
libxl: debug: libxl_event.c:1874:libxl__ao_complete: ao 0x1da77e0: complete, rc=0
libxl: debug: libxl_event.c:1843:libxl__ao__destroy: ao 0x1da77e0: destroy
xc: debug: hypercall buffer: total allocations:381 total releases:381
xc: debug: hypercall buffer: current allocations:0 maximum allocations:3
xc: debug: hypercall buffer: cache current size:3
xc: debug: hypercall buffer: cache hits:367 misses:3 toobig:11

**Comment by lukablurr** [comment]
Hello @musigit ,

Please try my fork [here](https://github.com/lukablurr/clickos), branch ``lukablurr/bugfix-issue40`` or simply apply this [patch](https://github.com/lukablurr/clickos/commit/0ea4184ed0422c59a80a4ed2418e9b9ee6dc904e) and tell us if it fixes your issue.

Thanks!

**Comment by musigit** [comment]
Hi,
I patched the diff, but it failed in the compilation of clickos. I attempted a clean build with a fresh git checkout.

Here is the error - 

../elements/minios/fromdevice.cc: In member function ‘virtual int FromDevice::initialize(ErrorHandler*)’:
../elements/minios/fromdevice.cc:90:10: error: invalid use of incomplete type ‘struct netfront_dev’
  if (_dev->netmap)
          ^
In file included from /home/tester/workspace/mini-os/include/mm.h:36:0,
                 from /home/tester/workspace/mini-os/include/x86/x86_64/hypercall-x86_64.h:39,
                 from /home/tester/workspace/mini-os/include/hypervisor.h:20,
                 from /home/tester/workspace/mini-os/include/x86/os.h:21,
                 from /home/tester/workspace/clickos/include/click/config-minios.h:174,
                 from /home/tester/workspace/clickos/include/click/config.h:297,
                 from ../elements/minios/fromdevice.hh:43,
                 from ../elements/minios/fromdevice.cc:40:
/home/tester/workspace/mini-os/include/lib.h:195:13: note: forward declaration of ‘struct netfront_dev’
      struct netfront_dev *dev;

**Comment by lukablurr** [comment]
Sorry for the inconvenience! I fixed the error, it should work now. Please do update you local clone and tell us if it's ok.

**Comment by musigit** [comment]
With the new patches, this issue is resolved. Thanks a lot.
