### ISSUE TITLE
Adding new click elements to clickos

### ISSUE THREAD

**Issue by muradkablan** [cnplab/clickos#5]
Hi,
I was able to launch clickos vms through your tutorial here http://cnp.neclab.eu/getting-started#clickos

I tested click on baremetel server where I was adding my own implemented and modified elements. I am not sure how I can do the same process with clickos.  
For example, 
- would modifying an element means that I have to build minos image all over again? 
- how can I debug my code withing clickos? in baremetal I could see my dmesg for example. But with clickos I'm limited by 1 console that doesn't let me interact with the vm. 

Please advise
Thanks,

**Comment by jpemartins** [comment]
Hi there!

Sorry for *long long* delay! 

To add new elements to ClickOS you can do it similar to how click does it: you simply add a folder in [minios/config.mk.in](https://github.com/cnplab/clickos/blob/master/minios/config.mk.in#L14) in the `CLICK_EXTRA_ELEMENT_GROUPS` variable and you  specifying the **folder name** where your elements are located **within the click elements**.

To debug your code, you can use something like `gdbsx -a <DOMAIN_ID> 64 60000` to run the server and `gdb -ex "target remote localhost:60000" -d <CLICKOS_PATH> -d <MINIOS_PATH> <IMAGE_PATH>`, to attach the debugger. You can then debug like a traditional application.

Cheers

**Comment by szabodavid** [comment]
Hi,

            we have a quite similar but somehow different problem. We would
            like to add a custom element we created, which depends on an
            external library. Unfortunately this one requires the std=c++0x flag
            (as we know this means a newer compiler version of c++). However, if
            we try to configure ClickOS with this flag we get errors for the
            basic elements.

            Certainly first we created our custom element only using Click and
            there the std=c++0x flag works perfectly with configure and make
            commands. So our problem starts only when we want to add this new
            element to ClickOS in order to make a minios image that should
            comprise it.

            Could you please give us an advice how to bypass this compiler
            problem? (If we want to add a custom element that doesn't depends on
            external library, then it works fine!)

**Comment by fmanco** [comment]
We need more information. Exactly what is the error? Which code/libraries are you trying to build? etc.
