### ISSUE TITLE
Container-based ClickOS virtualization

### ISSUE THREAD

**Issue by lbondan** [cnplab/clickos#8]
I want to virtualize ClickOS VMs using container-based virtualization, but I think ClickOS is restricted to be used with Xen-based management.
More specifically, I'm interested in use ClickOS together with CoreOS (https://github.com/coreos), which uses Docker for container management.
Maybe Xen optimizations made to improve ClickOS's packet processing turn it not possible, but I'm not sure.
Do you have any ideia if this compatibility is possible?

Thank you,

**Comment by fmanco** [comment]
Hi

ClickOS is basically a port of Click to run on Mini-OS, a minimalistic operative system that is Xen specific. But Click can be built for different targets, namely as a user-level application. Therefore you can simply build the `userlevel` target and run the application inside a container. This has nothing to do with ClickOS then, and is simply Click.

Best
-- Filipe
